//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiftClubDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lift
    {
        public System.Guid Lift1 { get; set; }
        public string CarType { get; set; }
        public int TotalSpace { get; set; }
        public int SpaceAvailable { get; set; }
        public Nullable<bool> PreferredRace { get; set; }
        public Nullable<bool> PreferredGender { get; set; }
        public System.DateTime MornigPickUpTime { get; set; }
        public System.DateTime EveningPickUpTim { get; set; }
        public string SuburbFrom { get; set; }
        public string SuburbTo { get; set; }
        public Nullable<decimal> Charge { get; set; }
        public string ServiceName { get; set; }
        public bool Monday { get; set; }
        public bool Tuesday { get; set; }
        public bool Wednesday { get; set; }
        public bool Thursday { get; set; }
        public bool Friday { get; set; }
        public bool Saturday { get; set; }
        public bool Sunday { get; set; }
        public System.Guid PersonalID { get; set; }
    
        public virtual Personal Personal { get; set; }
    }
}
