//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiftClubDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personal
    {
        public Personal()
        {
            this.Lifts = new HashSet<Lift>();
        }
    
        public System.Guid PersonalID { get; set; }
        public string Name { get; set; }
        public string CellNumber { get; set; }
        public bool Gender { get; set; }
        public string Email { get; set; }
        public System.Guid RoleD { get; set; }
    
        public virtual ICollection<Lift> Lifts { get; set; }
        public virtual Role Role { get; set; }
    }
}
